name: Deploy

on: # 在master分支上提交代码执行
  push:
    branches: [master]

jobs: # 作业
  build-and-deploy: # 作业名称
    runs-on: ubuntu-latest # 运行的环境

    steps: #步骤
      - name: Checkout # 步骤名
        uses: actions/checkout@v2 # 所使用的action

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Build Project
        run: npm run build

      - name: Deploy to Server
        uses: hengkx/ssh-deploy@v1.0.1
        with: # 以下为参数
          USERNAME: ${{ secrets.USER }} # 为了用户信息安全对敏感数据可以在secrets中配置请看下图
          PASSWORD: ${{ secrets.PASSWORD }}
          HOST: ${{ secrets.HOST }}
          SOURCE: "dist"
          TARGET: "/www/wwwroot"
          # AFTER_COMMAND: "npm run stop && npm install --production && npm run start"
